import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider"
import { ChakraProvider, defaultSystem } from "@chakra-ui/react"
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
       <body className="min-h-full flex flex-col" style={{ isolation: "isolate" }}>
         

        {/* Wrap children with the new client Provider */}
        <Provider>
             <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
